---
- hosts: all
  become: true

  tasks:
    - name: Install required system packages
      apt: 
        name: "{{ item }}"
        state: present  
        update_cache: yes
      loop: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    
    - name: Add GPG Key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Install Docker
      apt:
         name: "{{ item }}"
         state: latest
         update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose

    - name: Check Docker
      service: 
        name: docker
        state: stared
        enabled: yes
    
